In [1]:
import numpy as np


In [3]:
array1=np.array([1,2,-3,5,-6,7])

In [5]:
array1

array([ 1,  2, -3,  5, -6,  7])

In [11]:
negation=-array1
negation

array([-1, -2,  3, -5,  6, -7])

In [13]:
print("Absolute value:",np.abs(array1))

Absolute value: [1 2 3 5 6 7]


In [23]:
sq=np.sqrt(array1)
print("Square root of each element:\n",sq)


Square root of each element:
 [1.         1.41421356        nan 2.23606798        nan 2.64575131]


C:\Users\komal\AppData\Local\Temp\ipykernel_21436\3245920461.py:1: RuntimeWarning: invalid value encountered in sqrt
  sq=np.sqrt(array1)


In [21]:
print("Exponential value for each element:\n",np.exp(array1))

Exponential value for each element:
 [2.71828183e+00 7.38905610e+00 4.97870684e-02 1.48413159e+02
 2.47875218e-03 1.09663316e+03]


In [25]:
print("Sine value:\n",np.sin(array1))

Sine value:
 [ 0.84147098  0.90929743 -0.14112001 -0.95892427  0.2794155   0.6569866 ]


In [27]:
print("Cos value:\n",np.cos(array1))

Cos value:
 [ 0.54030231 -0.41614684 -0.9899925   0.28366219  0.96017029  0.75390225]


In [29]:
print("Tan value:\n",np.tan(array1))

Tan value:
 [ 1.55740772 -2.18503986  0.14254654 -3.38051501  0.29100619  0.87144798]


In [37]:
array2=np.array([6,7,8,9,1,2])
array2

array([6, 7, 8, 9, 1, 2])

In [39]:
print("Addition of two array is:\n",array1+array2)

Addition of two array is:
 [ 7  9  5 14 -5  9]


In [41]:
print("Substtraction of two array is:\n",array1-array2)


Substtraction of two array is:
 [ -5  -5 -11  -4  -7   5]


In [43]:
print("Multiplication of two array is:\n",array1*array2)


Multiplication of two array is:
 [  6  14 -24  45  -6  14]


In [47]:
print("Division of two array is:\n",array2/array1)


Division of two array is:
 [ 6.          3.5        -2.66666667  1.8        -0.16666667  0.28571429]


In [49]:
print("Modulus of two array is:\n",array1%array2)


Modulus of two array is:
 [1 2 5 5 0 1]


In [51]:
print("power of two array is:\n",array1**array2)


power of two array is:
 [      1     128    6561 1953125      -6      49]


In [53]:
print("Bitwise AND operator:\n",np.bitwise_and(array1,array2))


Bitwise AND operator:
 [0 2 8 1 0 2]


In [55]:
print("Bitwise OR operator:\n",np.bitwise_or(array1,array2))

Bitwise OR operator:
 [ 7  7 -3 13 -5  7]


In [59]:
print("Bitwise NOT operator:\n",np.invert(array1))

Bitwise NOT operator:
 [-2 -3  2 -6  5 -8]


In [61]:
print("Left shift by 1:\n",np.left_shift(array1,1))

Left shift by 1:
 [  2   4  -6  10 -12  14]


In [63]:
print("Rigth shift by 1:\n",np.right_shift(array1,1))

Rigth shift by 1:
 [ 0  1 -2  2 -3  3]
