In [3]:
import numpy as np
import array as arr


In [17]:
array1=arr.array('i',[1,2,3,4,5])
array1

array('i', [1, 2, 3, 4, 5])

In [29]:
for element in array1:
    print(element)


1
2
3
4
5


In [31]:
numpy_array=np.array([1,2,3])

In [39]:
print(numpy_array)


[1 2 3]


In [41]:
numpy_array1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [43]:
numpy_array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
zero_array=np.zeros(3)
zero_array

array([0., 0., 0.])

In [53]:
ones_array=np.ones(3)
ones_array

array([1., 1., 1.])

In [61]:
range=np.arange(1,10,2)
range

array([1, 3, 5, 7, 9])

In [71]:
random=np.random.rand(2,3)
print(random)

[[0.99659476 0.89862225 0.0901214 ]
 [0.82285274 0.26704568 0.48839189]]
