In [1]:
import numpy as np

In [7]:
array1=np.array([[1,2,3,4],[2,2,3,4],[5,6,7,8]])

In [9]:
print(array1)

[[1 2 3 4]
 [2 2 3 4]
 [5 6 7 8]]


In [11]:
print(array1[0,1])

2


In [13]:
print(array1[0,3])

4


In [15]:
print(np.sum(array1))

47


In [31]:
print(np.mean(array1,axis=1))

[2.5  2.75 6.5 ]


In [70]:
array2=np.array([[33,3],[3,79],[2,3]])
array2

array([[33,  3],
       [ 3, 79],
       [ 2,  3]])

In [80]:
array3=np.array([[1,2],[3,4],[5,6]])
array3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [86]:
np.dot(array2,array3.T)

array([[ 39, 111, 183],
       [161, 325, 489],
       [  8,  18,  28]])