In [1]:
import numpy as np

In [3]:
number=np.array([1,2,3,4,5])
number

array([1, 2, 3, 4, 5])

In [13]:
print(number[0])
print(number[1])
print(number[2])

1
2
3


In [17]:
number[2]=13
number

array([ 1,  2, 13,  4,  5])

In [19]:
number[-1]

5

In [39]:
number=np.array([[[1,2,3],[4,5,6],[7,8,9],[2,3,6]]])
number

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [2, 3, 6]]])

In [41]:
print(number[0,1,2])

6
